### ISSUE TITLE
run_step variable is used as both string and int in master_call.py with no checks for type.

### ISSUE THREAD

**Issue by davidmatten** [ColinAnthony/NGS_processing_pipeline#9]
Line 292:
            run_step = "break"
Line 295:
        run_step += 1

Traceback (most recent call last):
  File "/opt/software/hivdiv/NGS_processing_pipeline/step_2_ngs_processing_pipeline_master_call.py", line 668, in <module>
    user_ref, cores)
  File "/opt/software/hivdiv/NGS_processing_pipeline/step_2_ngs_processing_pipeline_master_call.py", line 295, in main
    run_step += 1
TypeError: Can't convert 'int' object to str implicitly

**Comment by ColinAnthony** [comment]
fixed line 292.
run_step = 100 to signal terminal error with the run.
